#+TITLE: Libtouch
#+DESCRIPTION: Libtouch is a library for touch gestures created under the guidance of the Sway project.

* API
** Target
Represents an area or region on the screen.
** Action
Represents one action, one part of a gesture.
The possible actions are
- Touch
- Move
- Rotate
- Pinch
- Delay
Each action can have
*** Treshold
Decides how much/how many/etc the action must be performed. E.g. the number of fingers for a touch, or the lenght of a movement.
*** Target
Where the action must take place. A movement is considered complete when it reaches the target.
*** 
** Gesture
A gesture is a series of actions, each must be completed before the next begins.
** Engine
The `libtouch_engine` is responsible for controlling the internal state. i.e. deciding which gestures are progressing, and how much.

The inner state is updated through the functions

#+BEGIN_SRC sh :wrap src C :exports results
libtouch_engine_register_move
libtouch_engine_register_touch
#+END_SRC

* Examples
See [[file:examples.c][examples.c]]
