#+TITLE: Libtouch
#+DESCRIPTION: Libtouch is a library for touch gestures created under the guidance of the Sway project.

* API
THIS IS A WIP
** Target
Represents an area or region on the screen. within which an action must take place.

For movement actions, it represents where the movement must end.
** Action
Represents one action, one part of a gesture.
The possible actions are
- Touch
- Move
- Rotate
- Pinch
- Delay
Each action can have
*** Treshold
Decides how much/how many/etc the action must be performed. E.g. the number of fingers for a touch, or the lenght of a movement.
*** Target
Where the action must take place. A movement is considered complete when it reaches the target.
*** Duration
Maximum duration within which an action must take place.
*** Move Tolerance
How much is minimum movement, before it is regarded as actual movement. E.g. a tap and hold may move X pixels without being regarded as a swipe, or how much movement in the "wrong" direction is allowed.
** Gesture
A gesture is a series of actions, each must be completed before the next begins.
** Engine
The `libtouch_engine` is responsible for controlling the memory allocation and freeing of other structures, as well as keeping them nice and tidy to be able to check them all.

The inner state is updated through the functions

#+BEGIN_SRC C
libtouch_engine_register_move
libtouch_engine_register_touch
#+END_SRC

* Examples
See [[file:examples.c][examples.c]]
